schema_version: "1.0"
model_id: retinaface_detect
version: "1.0.0"
category: cnn_detect
backend: rknn2_local
compatible:
  - soc: rk3576
    min_npu_driver: null
files:
  - path: model.rknn
    role: model_graph
    sha256: "caf90e0935a76e49939f71dde8f41efed5146cfc32da9165a068771a2b2fcb11"
    size: 1417059
input:
  width: 320
  height: 320
  format: bgr
  resize_mode: letterbox
  padding_value: 0
  mean: [0.0, 0.0, 0.0]
  std: [255.0, 255.0, 255.0]
postprocess:
  type: retinaface
  conf_threshold: 0.5
  nms_threshold: 0.4
